name: Gareth du Plooy's blog
description: Blogging about code
meta_description: "Your New Jekyll Site, Blogging about stuffs"
year: 2017

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Gareth du Plooy'
